#Patient data

centre_tbs <- rep (1, each = a)
rregistration_tbs <-rep (1, each = a)
rinpatient_tbs <- sample (0, size = a, replace = TRUE)
rwaiting_time_tbs <- sample(1:1000, size = a, replace = TRUE)
rage_tbs <- sample(18:75, size = a, replace = TRUE)
rgender_tbs <- rep (1, each = a)
rdisease_primary_tbs <- rep (1, each = a)
rdisease_secondary_tbs <- rep (10, each = a)
rdisease_tertiary_tbs <- rep (10, each = a)
previous_tx_tbs <- rep (0, each = a)
rprevious_surgery_tbs <- rep (0, each = a)
rbilirubin_tbs <- sample(5:20, size = a, replace = TRUE)
rinr_tbs <- rep (1, each = a)
rcreatinine_tbs <- sample(50:100, size = a, replace = TRUE)
rrenal_tbs <- rep (0, each = a)
rsodium_tbs <- sample(135:145, size = a, replace = TRUE)
rpotassium_tbs <-  sample(3.5:5, size = a, replace = TRUE)
ralbumin_tbs <- sample(30:40, size = a, replace = TRUE)
rencephalopathy_tbs  <- rep (0, each = a)
rascites_tbs  <- rep (0, each = a)
rdiabetes_tbs  <- rep (0, each = a)
rmax_afp_tbs  <- rep (5, each = a)
rtumour_number_tbs  <- rep (1, each = a)
rmax_tumour_size_tbs <- rep (2, each = a)
dage_tbs <- sample(20:75, size = a, replace = TRUE)
dcause_tbs <- rep (1, each = a)
dbmi_tbs <-  sample(20:40, size = a, replace = TRUE)
ddiabetes_tbs <- rep (0, each = a)
dtype_tbs <- rep (0, each = a)
splittable_tbs <- rep (0, each = a)
bloodgroup_compatible_tbs <- rep (0, each = a)

?sample()
?rep()

a <- 2

centre_tbs <- sample (1:7, size= a, replace = TRUE)